[package]
name = "to"
version = "0.1.0"
authors = ["Jose Albizures <albizures3601@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.18"
serde = "1.0.99"
dirs = "2.0.2"
serde_json = "1.0.40"
